# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 16.0
      run: sudo xcode-select -s /Applications/Xcode_16.0.app
    - name: Build
      run: xcodebuild -scheme Flash -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -disableAutomaticPackageResolution
    - name: Run tests
      run: xcodebuild test -scheme Flash -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -disableAutomaticPackageResolution
