name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v5
    - name: Select Xcode 16.0
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    - name: Build
      run: xcodebuild -scheme Flash -destination "platform=iOS Simulator,OS=latest,name=iPhone 17" -disableAutomaticPackageResolution
    - name: Run tests
      run: xcodebuild test -scheme Flash -destination "platform=iOS Simulator,OS=latest,name=iPhone 17" -disableAutomaticPackageResolution
